# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(652, 482)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 651, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.control_bt = QtWidgets.QPushButton(self.tab)
        self.control_bt.setGeometry(QtCore.QRect(290, 390, 310, 30))
        self.control_bt.setObjectName("control_bt")
        self.label_judulSuhu = QtWidgets.QLabel(self.tab)
        self.label_judulSuhu.setGeometry(QtCore.QRect(40, 190, 220, 31))
        self.label_judulSuhu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judulSuhu.setObjectName("label_judulSuhu")
        self.label_judulKet = QtWidgets.QLabel(self.tab)
        self.label_judulKet.setGeometry(QtCore.QRect(40, 320, 220, 31))
        self.label_judulKet.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judulKet.setObjectName("label_judulKet")
        self.label_judulNama = QtWidgets.QLabel(self.tab)
        self.label_judulNama.setGeometry(QtCore.QRect(40, 60, 220, 31))
        self.label_judulNama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judulNama.setObjectName("label_judulNama")
        self.label_header = QtWidgets.QLabel(self.tab)
        self.label_header.setGeometry(QtCore.QRect(230, 20, 191, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.label_suhu_2 = QtWidgets.QLabel(self.tab)
        self.label_suhu_2.setGeometry(QtCore.QRect(40, 220, 220, 81))
        self.label_suhu_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_suhu_2.setObjectName("label_suhu_2")
        self.label_nama = QtWidgets.QLabel(self.tab)
        self.label_nama.setGeometry(QtCore.QRect(40, 90, 220, 81))
        self.label_nama.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nama.setObjectName("label_nama")
        self.label_keterangan = QtWidgets.QLabel(self.tab)
        self.label_keterangan.setGeometry(QtCore.QRect(40, 350, 220, 71))
        self.label_keterangan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_keterangan.setObjectName("label_keterangan")
        self.image_label = QtWidgets.QLabel(self.tab)
        self.image_label.setGeometry(QtCore.QRect(290, 60, 310, 310))
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QLineEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(40, 90, 220, 81))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 330, 220, 40))
        self.pushButton.setObjectName("pushButton")
        
        self.textEdit_username = QtWidgets.QLineEdit(self.tab_2)
        self.textEdit_username.setGeometry(QtCore.QRect(40, 220, 220, 81))
        self.textEdit_username.setObjectName("textEdit_username")
        self.textEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        
        self.label_header_2 = QtWidgets.QLabel(self.tab_2)
        self.label_header_2.setGeometry(QtCore.QRect(230, 20, 191, 22))
        self.label_input = QtWidgets.QLabel(self.tab_2)
        self.label_input.setGeometry(QtCore.QRect(40, 60, 220, 30))
        self.label_input.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input.setStyleSheet("background-color: darkblue; color: white;")
        self.label_username = QtWidgets.QLabel(self.tab_2)
        self.label_username.setGeometry(QtCore.QRect(40, 190, 220, 30))
        self.label_username.setAlignment(QtCore.Qt.AlignCenter)
        self.label_username.setStyleSheet("background-color: darkblue; color: white;")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_header_2.setFont(font)
        self.label_header_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_header_2.setObjectName("label_header_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.image_qr = QtWidgets.QLabel(self.tab_2)
        self.image_qr.setGeometry(QtCore.QRect(290, 60, 310, 310))
        self.image_qr.setAlignment(QtCore.Qt.AlignCenter)
        self.image_qr.setObjectName("image_qr")
        self.image_qr.setStyleSheet("background-color: white;")
        self.buttonSaveImage = QtWidgets.QPushButton(self.tab_2)
        self.buttonSaveImage.setGeometry(QtCore.QRect(290, 390, 150, 30))
        self.buttonSaveImage.setObjectName("buttonSaveImage")
        self.buttonClear = QtWidgets.QPushButton(self.tab_2)
        self.buttonClear.setGeometry(QtCore.QRect(450, 390, 150, 30))
        self.buttonClear.setObjectName("buttonClear")
        #Form.setCentralWidget(self.centralwidget) 

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Absensi v1.0"))
        self.control_bt.setText(_translate("Form", "Scan BarCode"))
        self.label_judulSuhu.setText(_translate("Form", "Suhu"))
        self.label_judulKet.setText(_translate("Form", "Keterangan"))
        self.label_judulNama.setText(_translate("Form", "Nama"))
        self.label_header.setText(_translate("Form", "Absensi & Tracing User"))
        self.label_suhu_2.setText(_translate("Form", "-"))
        self.label_nama.setText(_translate("Form", "-"))
        self.label_judulNama.setStyleSheet("background-color: darkblue; color: white;")
        self.label_nama.setStyleSheet("background-color: white;")
        self.label_judulSuhu.setStyleSheet("background-color: darkblue; color: white;")
        self.label_suhu_2.setStyleSheet("background-color: white;")
        self.label_judulKet.setStyleSheet("background-color: darkblue; color: white;")
        self.label_keterangan.setStyleSheet("background-color: white;")
        self.image_label.setStyleSheet("background-color: white;")
        self.label_keterangan.setText(_translate("Form", "-"))
        self.image_label.setText(_translate("Form", "Scan Suhu Anda"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Home"))
        self.pushButton.setText(_translate("Form", "Create"))
        self.buttonSaveImage.setText(_translate("Form", "Save QR Code"))
        self.buttonClear.setText(_translate("Form", "Clear QR Code"))
        self.label_header_2.setText(_translate("Form", "Buat Data User Baru"))
        self.label_input.setText(_translate("Form", "Input Nama"))
        self.label_username.setText(_translate("Form", "Buat ID User Baru"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "New User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

